# Generated by Django 5.2.17 on 2026-08-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="configuration",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
